--- #YAML:1.0
name:               Reddit-Client
version:            0.04
abstract:           A perl wrapper for Reddit
author:
    - "Jeff Ober" <"jeffober@gmail.com">
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:        0
    IO::Capture::Stderr:  0
    JSON:                 0
    List::Util:           0
    LWP::UserAgent:       0
    Test::MockModule:     0
    Test::More:           0
    URI::Encode:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
