---
abstract: 'A perl wrapper for Reddit'
author:
  - "\"Jeff Ober\" <\"jeffober@gmail.com\">"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reddit-Client
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  IO::Capture::Stderr: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Util: 0
  Test::MockModule: 0
  Test::More: 0
  URI::Encode: 0
version: 0.04_02
